server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
     gateway:
       routes:
         - id: CATALOGUE-SERVICE
           uri: lb://CATALOGUE-SERVICE
           predicates:
             - Path=/catalogue/**
         - id: INVENTORY-SERVICE
           uri: lb://INVENTORY-SERVICE
           predicates:
             - Path=/inventory/**
         - id: INHANDPRODUCTS-SERVICE
           uri: lb://INHANDPRODUCTS-SERVICE
           predicates:
             - Path=/GetInHandProduct/**

  main:
    web-application-type: reactive

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka:8761/eureka
